services:
  app:
    entrypoint:
    - sleep
    - infinity
    image: python:3.10.6-slim
    init: true
    volumes:
    - type: bind
      source: /var/run/docker.sock
      target: /var/run/docker.sock

